on:
  push:
    branches:
      - main
      - automatic-update

name: run-mapping-and-tests

jobs:
  run-mapping-and-tests:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Run mapping
        run: |
          source("src/run_dwc_mapping.R")
        shell: Rscript {0}

      - name: Commit changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "Map to DwC"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          source("tests/test_dwc_occurrence.R")
        shell: Rscript {0}
